Add one very basic Cypress test
CodeForPhilly/chime pull request #128
Opened 2020-03-20 02:28 UTC by garysieling

This adds one Cypress test - it clicks on the + indicators on the right and makes sure the first one updates.

This unlocks having something that hits the main site, or tests things that aren't amenable to testing through Python unit tests, like the issue about the site title being wrong.

2020-03-21 18:55 UTC, themightychris requested changes
one small update is needed before merge, looks good otherwise!

2020-03-21 18:55 UTC, themightychris commented on .github/workflows/pythonapp.yml
> +        streamlit run app.py &
@garysieling update per #169 to

```suggestion
        streamlit run src/app.py &
```

2020-03-22 01:53 UTC, garysieling commented
Applied the change & updated the test since it's returning a new value now

2020-03-22 05:58 UTC, themightychris approved these changes

2020-03-22 05:58 UTC, merged