Update public instance in developer documentation to Linode 1.1.2
CodeForPhilly/chime pull request #511
Opened 2020-04-08 17:27 UTC by dsgit1

Updated public instance in developer documentation from 1.1.0 Heroku instance to 1.1.2 Linode instance.

2020-04-08 17:38 UTC, themightychris commented
The Linode instance is the main link at the top of this article, the Heroku link is provided as an alternative in case the main link were to be down.

Do we know whether that Heroku instance has been getting kept up-to-date by anyone? We've automated through github deployment of the `develop` branch to another heroku account, we could replicate that to automate updating that production alternative heroku instance on release alongside updating Linode

2020-04-09 01:57 UTC, jlubken commented
Heroku deploy was back at v1.1.0, I'm updating to deploy develop right now and will likely go back to v1.1.1 once I confirm that the develop works.

2020-04-09 03:28 UTC, jlubken commented on docs/getting-started/try-online.md
> +Try this link: https://penn-chime.phl.io/
I think this is supposed to be an alternative to Linode on line 3. Ask @mdbecker if he would update the heroku instance to v1.1.2.

2020-04-09 03:29 UTC, jlubken requested changes
I think we want to keep the heroku reference.

2020-04-10 01:52 UTC, dsgit1 commented
Understood. Will close this.

2020-04-10 01:52 UTC, closed without merging